### ISSUE TITLE
reductions stuff

### ISSUE THREAD

**Issue by timm** [ai-se/XTREES#52]
is in the last few lines of intro and 5.1.1 and in the example of 5.1.3 and dot points of 5.2.1 and fig 10,11 and i dont know where else.

make sure when we flip R to 1-R all those changes get updated

**Comment by rahlk** [comment]
Also #46 —
Generally a higher performance is expressed as a higher value, so in the report tables I would suggest reporting % reduction (e.g., 35%) instead of the new median (65%)

**TODO: Replace after/before by (1 - after/before) x 100%**
- [x] Last few lines of 5.1.1
- [x] Abstract (change the wording) 
- [ ] Abstract (change the median)
- [x] Section 5.1.3 
- [x] Example of 5.1.3
- [ ] Bullets in 5.2.1
- [x] Fig 9  
- Fig 10
  - [x] Ant
  - [x] Ivy
  - [x] Lucene
  - [x] Jedit
  - [x] Poi
- Fig 11
  - [x] Apache
  - [x] BDBJ
  - [x] BDBC
  - [x] LLVM
  - [x] x264
  - [x] SQL
- [x] Fig 14

**Comment by timm** [comment]
remmebr to run all the quartiles 0 to 100 not just min max of the samples before you.
